### ISSUE TITLE
Loading overlay blocks browser navigation buttons

### ISSUE THREAD

**Issue by vcpstudio** [logue/vite-vuetify-ts-starter#16]
https://github.com/logue/vite-vuetify-ts-starter/blob/d013cbe9b53fa8d8133bc7dc84ba831bf2668d92/src/App.vue#LL109C8-L109C8

If you do not set the close-on-back="false" attribute, then there will be problems when working with browser navigation buttons (back/forward)

https://vuetifyjs.com/en/api/v-overlay/#props-close-on-back

**Comment by logue** [comment]
It is a specification that it remains displayed when a script error occurs and becomes inoperable.
This loading screen is processed on the Pinia side.
https://github.com/logue/vite-vuetify-ts-starter/blob/d013cbe9b53fa8d8133bc7dc84ba831bf2668d92/src/store/GlobalStore.ts#L17-L28

For example, when a communication error occurs in `axios`, it is necessary to implement a process to manually turn off the loading screen as follows.

```ts
import axios, { type AxiosProgressEvent, type AxiosResponse } from 'axios';
import { useGlobal } from '@/store';

axios.defaults.headers.common['X-Requested-With'] = 'XMLHttpRequest';
axios.defaults.headers.common.Accept = 'application/json';
axios.defaults.withCredentials = true;
axios.defaults.onUploadProgress = (progressEvent: AxiosProgressEvent): void => {
  const globalStore = useGlobal();
  if (progressEvent.progress && progressEvent.total) {
    globalStore.setProgress(
      Math.round((progressEvent.loaded * 100) / progressEvent.total)
    );
  } else {
    globalStore.setProgress(null);
  }
  nextTick();
};
axios.defaults.onDownloadProgress = (
  progressEvent: AxiosProgressEvent
): void => {
  const globalStore = useGlobal();
  if (progressEvent.progress && progressEvent.total) {
    globalStore.setProgress(
      Math.round((progressEvent.loaded * 100) / progressEvent.total)
    );
  } else {
    globalStore.setProgress(null);
  }
  nextTick();
};
axios.interceptors.request.use(request => {
  const globalStore = useGlobal();
  globalStore.setLoading(true);
  return request;
});
axios.interceptors.response.use(
  (response: AxiosResponse<any, any>) => {
    const globalStore = useGlobal();
    globalStore.setLoading(false);
    return response;
  },
  async error => {
    const globalStore = useGlobal();
    
    globalStore.setMessage('An unknown error has occurred.');
    globalStore.setLoading(false);
    // location.reload();
    throw new Error(error);
    globalStore.setLoading(false);
    console.log(error.response.data);
    return await Promise.reject(error);
  }
);
```

**Comment by vcpstudio** [comment]
Recorded a video for a visual example:

![2023-05-22 13-20-52](https://github.com/logue/vite-vuetify-ts-starter/assets/4546015/1d1ca571-d469-4104-a4c4-b82477d6a712)

**Comment by logue** [comment]
Fixed.

**Comment by vcpstudio** [comment]
I liked the page loader indicator idea, but your fix removed it

**Comment by logue** [comment]
This is a provisional measure.

Due to various reasons (TypeScript5 compatibility, vitest issues, etc.), this is a last resort for the significant delay in release.

Since the idea used in Vuetify2 was diverted as it is, there were parts that did not work properly.
