### ISSUE TITLE
Performance Issues and Vuetify Plugin Problems in Your Project

### ISSUE THREAD

**Issue by JunYoungMoon** [logue/vite-vuetify-ts-starter#17]
I'm using your project for web development, but it's so slow that I'm unsure if I can deploy it. Is it a problem with the Vuetify plugin? I've tried commenting out "styles: { configFile: 'src/styles/settings.scss' }" based on other issues, but it's still slow.

**Comment by logue** [comment]
This template project provides access to all APIs for customizing Vuetify. As a result, compiling operations occur at startup, making operation slow.

Please try setting the value of `autoImport` in vite.config.ts to false.
