### ISSUE TITLE
import colors from vuetify/lib/util/colors

### ISSUE THREAD

**Issue by f1eeman** [logue/vite-vuetify-ts-starter#4]
![image](https://user-images.githubusercontent.com/49826703/200255591-925a7ebe-da07-42af-a642-66a12b905094.png)
Eslint doesn't see imports

**Comment by logue** [comment]
I don't know because there is no type definition on the Vuetify side.
For the time being, please add .mjs and import it after disabling the error as follows.

```
// @ts-ignore
import colors from 'vuetify/lib/util/colors.mjs';
```

**Comment by f1eeman** [comment]
ok, thanks
