### ISSUE TITLE
type declaration

### ISSUE THREAD

**Issue by f1eeman** [logue/vite-vuetify-ts-starter#7]
vscode
![image](https://user-images.githubusercontent.com/49826703/203785974-7350d2e8-8298-4970-859a-d2f1aa129317.png)
![image](https://user-images.githubusercontent.com/49826703/203786057-b9deac76-9d03-409f-a274-79931ae16189.png)

**Comment by logue** [comment]
[Veutr](https://marketplace.visualstudio.com/items?itemName=octref.vetur) does not support it. Use [Volar](https://marketplace.visualstudio.com/items?itemName=Vue.volar).

**Comment by f1eeman** [comment]
solved
